spring:
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      key-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mongodb-authentication
      username: admin
      password: admin
      authentication-database: admin
kafka:
  topic:
    register: company-registration