spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER:localhost:29092}
    consumer:
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      key-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  data:
    mongodb:
      host: ${DATABASE_HOST:localhost}
      port: ${DATABASE_PORT:27017}
      database: ${DATABASE_NAME:mongodb-authentication}
      username: ${DATABASE_USERNAME:admin}
      password: ${DATABASE_PASSWORD:admin}
      authentication-database: ${AUTHENTICATION_DATABASE:admin}
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_EMAIL:}
    password: ${SMTP_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
kafka:
  topic:
    register: company-registration
    email-verified: email-verified

oauth:
  google:
    client-id: ${GOOGLE_CLIENT_ID:}
    client-secret: ${GOOGLE_CLIENT_SECRET:}
    redirect-uri: ${GOOGLE_LOGIN_REDIRECT_URL:http://localhost:5175/login/oauth2/code/google}
    token-uri: https://oauth2.googleapis.com/token
    user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
