server:
  port: 8082

spring:
  application:
    name: company-service
  
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: company-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.job.manager.dto

  data:
    mongodb:
      host: localhost
      port: 27018
      database: mongodb-company
      username: admin
      password: admin
      authentication-database: admin

kafka:
  topic:
    register: company-registration

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: localhost

logging:
  level:
    com.job.manager.company: DEBUG
    org.springframework.data.mongodb: DEBUG