server:
  port: 8081

spring:
  application:
    name: company-service
  
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER:localhost:29092}
    consumer:
      group-id: company-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.job.manager.dto,com.job.manager.subscription.dto
        spring.json.type.mapping: com.job.manager.subscription.dto.SubscriptionEventDTO:com.job.manager.company.dto.SubscriptionEventDTO

  data:
    mongodb:
      host: ${DATABASE_HOST:localhost}
      port: ${DATABASE_PORT:27018}
      database: ${DATABASE_NAME:mongodb-company}
      username: ${DATABASE_USERNAME:admin}
      password: ${DATABASE_PASSWORD:admin}
      authentication-database: ${AUTHENTICATION_DATABASE:admin}

kafka:
  topic:
    register: company-registration
    email-verified: email-verified
  topics:
    subscription-activated: subscription-activated
    subscription-cancelled: subscription-cancelled
    subscription-expired: subscription-expired

applicant:
  service:
    url: http://localhost:8084

logging:
  level:
    com.job.manager.company: DEBUG
    org.springframework.data.mongodb: DEBUG