spring:
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: company-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.job.manager.dto

  mongodb:
    host: localhost
    port: 27018
    database: mongodb-company
    username: admin
    password: admin
    authentication-database: admin

kafka:
  topic:
    register: company-registration