spring:
  data:
    mongodb:
      host: ${DATABASE_HOST:localhost}
      port: ${DATABASE_PORT:27020}
      database: mongodb-subscription
      username: admin
      password: admin
      authentication-database: admin
  application:
    name: subscription
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8083

# Kafka Topics
kafka:
  topics:
    subscription-created: subscription-created
    subscription-activated: subscription-activated
    subscription-expired: subscription-expired
    subscription-cancelled: subscription-cancelled
    payment-failed: payment-failed
    subscription-expiring-soon: subscription-expiring-soon

# Service URLs - Company Service for validation
company:
  service:
    url: http://localhost:8082

services:
  subscription:
    url: http://localhost:8083
    activate-endpoint: /subscriptions/{subscriptionId}/activate

stripe:
  api-key: ${STRIPE_API_KEY:sk_test_51ShMhN2UgzNIbDYO2uNw1uKmRoYCLZa1lZKvzSMpeRvBvxmN9IoRwnDGibvTULN83WwQfHFEIfaSAm4GUTBRyWAo00JY98AwiZ}
  success-url: ${STRIPE_SUCCESS_URL:http://localhost:5173/payment/success%7D
  cancel-url: ${STRIPE_CANCEL_URL:http://localhost:5173/payment/cancel%7D
  webhook-secret: ${STRIPE_WEBHOOK_SECRET:whsec_2484a92d3bb3c85ca12d8accccf6888fc9306d237a910cc0643ca03e9f980dd7} 
  #stripe listen --forward-to localhost:8083/webhook/stripe