spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER:localhost:29092}
    consumer:
      group-id: notification-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.job.manager.*
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_EMAIL:}
    password: ${SMTP_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    mongodb:
      host: ${DATABASE_HOST:localhost}
      port: ${DATABASE_PORT:27021}
      database: mongodb-notification
      username: admin
      password: admin
      authentication-database: admin        

services:
  authentication:
    base-url: ${AUTH_URL:http://localhost:8080/auth}
  subscription:
    base-url: ${SUBSCRIPTION_URL:http://localhost:8083}
  

kafka:
  topic:
    applicant-profile-updates: applicant-profile-updates
