spring:
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: job-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.job.manager.dto

  mongodb:
    host: localhost
    port: 27022
    database: mongodb-company
    username: admin
    password: admin
    authentication-database: admin

kafka:
  topic:
    job-updates: job-post-updates

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true