spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER:localhost:29092}
    consumer:
      group-id: job-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.job.manager.dto

  mongodb:
    host: ${DATABASE_HOST:localhost}
    port: ${DATABASE_PORT:27022}
    database: mongodb-company
    username: admin
    password: admin
    authentication-database: admin

kafka:
  topic:
    job-updates: job-post-updates