spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER:localhost:29092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: job-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.job.manager.dto
  data:
    mongodb:
      host: ${DATABASE_HOST:localhost}
      port: ${DATABASE_PORT:27022}
      database: ${DATABASE_NAME:mongodb-job}
      username: ${DATABASE_USERNAME:admin}
      password: ${DATABASE_PASSWORD:admin}
      authentication-database: ${AUTHENTICATION_DATABASE:admin}

server:
  port: 8082

kafka:
  topic:
    job-updates: job-post-updates
